spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://intellead-security-postgresql:5432/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect